name: Run benchmarks

# on:
#   workflow_dispatch:
#     inputs:
#       class:
#         description: 'Benchmark class'
#         required: false
#         default: '*'
#       jdk:
#         description: 'JDK version: 8 (default) or 11'
#         required: false
#         default: '8'

on:
  pull_request:
    branches:
    - master

jobs:
  # Build: build Spark and run the tests for specified modules.
  benchmark:
    name: "Run benchmarks: ${{ github.event.inputs.class }} (JDK ${{ github.event.inputs.jdk }})"
    # Ubuntu 20.04 is the latest LTS. The next LTS is 22.04.
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Spark repository
      uses: actions/checkout@v2
      # In order to get diff files
      with:
        fetch-depth: 0
    - name: Cache Scala, SBT and Maven
      uses: actions/cache@v2
      with:
        path: |
          build/apache-maven-*
          build/scala-*
          build/*.jar
          ~/.sbt
        key: build-${{ hashFiles('**/pom.xml', 'project/build.properties', 'build/mvn', 'build/sbt', 'build/sbt-launch-lib.bash', 'build/spark-build-info') }}
        restore-keys: |
          build-
#     - name: Cache Coursier local repository
#       uses: actions/cache@v2
#       with:
#         path: ~/.cache/coursier
#         key: benchmark-coursier-${{ github.event.inputs.jdk }}-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
#         restore-keys: |
#           benchmark-coursier-${{ github.event.inputs.jdk }}
    - name: Cache Coursier local repository
      uses: actions/cache@v2
      with:
        path: ~/.cache/coursier
        key: benchmark-coursier-11-${{ hashFiles('**/pom.xml', '**/plugins.sbt') }}
        restore-keys: |
          benchmark-coursier-11-
    # - name: Install Java ${{ github.event.inputs.jdk }}
    - name: Install Java 11
      uses: actions/setup-java@v1
      with:
        # java-version: ${{ github.event.inputs.jdk }}
        java-version: 11
    - name: Run benchmarks
#       run: |
#         ./build/sbt -Pyarn -Pmesos -Pkubernetes -Phive -Phive-thriftserver -Phadoop-cloud -Pkinesis-asl -Pspark-ganglia-lgpl test:package
#         SPARK_GENERATE_BENCHMARK_FILES=1 bin/spark-submit --class org.apache.spark.benchmark.Benchmarks \
#           --jars "`find . -name "*-SNAPSHOT-tests.jar" | paste -sd ',' -`" "`find . -name "spark-core*-SNAPSHOT-tests.jar`" ${{ github.event.inputs.class }}
#         echo "::set-output name=DIFF_LIST::`git diff --name-only`"
      run: |
        ./build/sbt -Pyarn -Pmesos -Pkubernetes -Phive -Phive-thriftserver -Phadoop-cloud -Pkinesis-asl -Pspark-ganglia-lgpl test:package
        # In benchmark, we use local as master so set driver memory only. Note that GitHub Actions has 7 GB memory limit.
        SPARK_GENERATE_BENCHMARK_FILES=1 bin/spark-submit --driver-memory 6g --class org.apache.spark.benchmark.Benchmarks \
          --jars "`find . -name '*-SNAPSHOT-tests.jar' | paste -sd ',' -`" "`find . -name 'spark-core*-SNAPSHOT-tests.jar'`" "*"
        # To keep the directory structure, tar them
        # See also https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files
        tar -cvf benchmark-results-11.tar `git diff --name-only`
    - name: Upload benchmark results
      uses: actions/upload-artifact@v2
      with:
        # name: benchmark-results-${{ github.event.inputs.class }}-${{ github.event.inputs.jdk }}
        name: benchmark-results-11
        path: benchmark-results-11.tar
